### ISSUE TITLE
Crash when resolving relative redirections

### ISSUE THREAD

**Issue by jaimeiniesta** [jaimeiniesta/funkspector#1]
Funkspector is having trouble handling relative redirections, like in this case:

``` elixir
iex(1)> Funkspector.scrape("http://elpais.com/tag/elecciones_eeuu_2016/a/")
** (exit) :badarg
         (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
        (hackney) src/hackney_connect.erl:245: :hackney_connect.do_connect/5
        (hackney) src/hackney_connect.erl:36: :hackney_connect.connect/5
        (hackney) src/hackney.erl:328: :hackney.request/5
      (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
    (funkspector) lib/funkspector/resolver.ex:5: Funkspector.Resolver.resolve/3
    (funkspector) lib/funkspector/scraper.ex:5: Funkspector.Scraper.scrape/1
```

This is what happens inside:

``` elixir
iex(1)> HTTPoison.get "http://elpais.com/tag/elecciones_eeuu_2016/a/"
{:ok,
 %HTTPoison.Response{body: "",
  headers: [{"Server", "nginx/1.3.5 epet/0.8.0.1"},
   {"Date", "Fri, 17 Jun 2016 22:12:04 GMT"},
   {"Content-Type", "text/html; charset=UTF-8"}, {"Content-Length", "0"},
   {"Connection", "keep-alive"}, {"Location", "/tag/elecciones_eeuu/a/"},
   {"Cache-Control", "no-cache"}, {"X-Accel-Cache-Control", "no-cache"},
   {"Set-Cookie",
    "uid=W9g/8VdkdbQgUD/nAx1wAg==#be7b57c396d64ecb390fa68ce44e3280; expires=Thu, 07-Jun-18 22:12:04 GMT; domain=.elpais.com; path=/; httponly"},
   {"P3P", "CP=\"CUR ADM OUR IND STA NID\""}], status_code: 302}}
iex(2)> HTTPoison.get "/tag/elecciones_eeuu/a/"
** (exit) :badarg
       (kernel) gen_tcp.erl:149: :gen_tcp.connect/4
      (hackney) src/hackney_connect.erl:245: :hackney_connect.do_connect/5
      (hackney) src/hackney_connect.erl:36: :hackney_connect.connect/5
      (hackney) src/hackney.erl:328: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
```

To fix that we need to handle relative links in order to merge them with the base URL, we're waiting for Elixir 1.3 to implement this more easily.

**Comment by jaimeiniesta** [comment]
Fixed in 0.0.2.
